# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend-deployment
  labels:
    app: fastapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-container
        image: leandro282/projeto-kubernetes-pb-desafio-jenkins-backend:{{tag}}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
spec:
  selector:
    app: fastapi-backend
  ports:
  - port: 80 # Porta do Service (interna ao cluster)
    targetPort: 8000 # Porta do contêiner (FastAPI)
    nodePort: 30001 # Porta externa no nó para o BACKEND
  type: NodePort