# k8s/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-container
        image: leandro282/projeto-kubernetes-pb-desafio-jenkins-frontend:{{tag}}
        ports:
        - containerPort: 80 # Porta que o Nginx expõe no contêiner React
    # Note: A variável REACT_APP_API_BASE_URL para o frontend no Kubernetes
    # será injetada no Dockerfile durante o build pelo Jenkins,
    # apontando para o Service do backend: http://fastapi-backend-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 80 # Porta do Service (interna ao cluster)
    targetPort: 80 # Porta do contêiner (Nginx)
    nodePort: 30000 # Porta externa no nó para o FRONTEND
  type: NodePort