
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-container
        image: leandro282/projeto-kubernetes-pb-desafio-jenkins-frontend:{{tag}}
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 
    nodePort: 31001
  type: NodePort